name: motion_blur
description: A simple motion blur widget.
version: 0.0.1
homepage: https://github.com/jonaird/motion_blur

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_shaders: ^0.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
